export interface AvatarFrame {
  id: string;
  name: string;
  category: "Cosmos" | "Cyberpunk" | "Místico" | "Imperial" | "Elemental";
  desc: string;
  borderGradient: string; // Tailwind linear-gradient or custom CSS gradient
  glowColor: string; // Shadow styling e.g., 'rgba(57, 137, 246, 0.4)'
  animationStyle: "spin-slow" | "pulse-glow" | "neon-flicker" | "rainbow-flow" | "fire-aura" | "stars-shimmer" | "retro-lines" | "matrix-rain" | "waves-flow" | "orbit-gems" | "none";
  requiredXp: number; // Gamified: unlock requirement (accumulated study XP)
  emojiSymbol?: string;
  badgeText?: string;
  badgeColor?: string;
  isPremiumOnly?: boolean;
}

export const AVATAR_FRAMES: AvatarFrame[] = [
  {
    id: "frame_owner",
    name: "Soberano Fundador",
    category: "Imperial",
    desc: "A moldura celestial suprema reservada exclusivamente para o ADM do Cosmos.",
    borderGradient: "linear-gradient(135deg, #fff2a3 0%, #ffd700 30%, #f1a80a 70%, #9a6b05 100%)",
    glowColor: "rgba(251, 191, 36, 0.85)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "👑",
    badgeText: "ADM",
    badgeColor: "bg-gradient-to-r from-amber-500 via-yellow-400 to-orange-500 font-black text-white border border-yellow-300 animate-pulse-slow shadow-[0_0_15px_rgba(251,191,36,0.5)]",
  },
  // CATEGORY: Cosmos
  {
    id: "frame_01",
    name: "Pioneiro Sideral",
    category: "Cosmos",
    desc: "A moldura de órbita padrão de todo iniciante do Cosmos.",
    borderGradient: "linear-gradient(135deg, #3b82f6 0%, #1e3a8a 100%)",
    glowColor: "rgba(59, 130, 246, 0.4)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "🚀",
    badgeText: "Iniciante"
  },
  {
    id: "frame_02",
    name: "Anel de Saturno",
    category: "Cosmos",
    desc: "Inspirada nos belos e finos discos de detritos congelados de Saturno.",
    borderGradient: "linear-gradient(45deg, #f59e0b 0%, #d97706 50%, #fef08a 100%)",
    glowColor: "rgba(245, 158, 11, 0.5)",
    animationStyle: "orbit-gems",
    requiredXp: 50,
    emojiSymbol: "🪐"
  },
  {
    id: "frame_03",
    name: "Nebulosa de Órion",
    category: "Cosmos",
    desc: "Uma névoa ultravioleta suave e reconfortante gerada no berço das estrelas.",
    borderGradient: "linear-gradient(135deg, #ec4899 0%, #8b5cf6 50%, #3b82f6 100%)",
    glowColor: "rgba(139, 92, 246, 0.6)",
    animationStyle: "pulse-glow",
    requiredXp: 100,
    emojiSymbol: "🌌"
  },
  {
    id: "frame_04",
    name: "Pulsar Ativo",
    category: "Cosmos",
    desc: "Raios magnéticos pulsantes de alta frequência das maiores estrelas de nêutrons.",
    borderGradient: "linear-gradient(90deg, #06b6d4 0%, #0891b2 50%, #22d3ee 100%)",
    glowColor: "rgba(6, 182, 212, 0.6)",
    animationStyle: "neon-flicker",
    requiredXp: 180,
    emojiSymbol: "☄️"
  },
  {
    id: "frame_05",
    name: "Buraco Negro Estelar",
    category: "Cosmos",
    desc: "A gravidade é tão forte que nem mesmo a luz do seu conhecimento pode escapar.",
    borderGradient: "linear-gradient(225deg, #1e1b4b 0%, #4c1d95 60%, #0f172a 100%)",
    glowColor: "rgba(76, 29, 149, 0.7)",
    animationStyle: "spin-slow",
    requiredXp: 280,
    emojiSymbol: "🕳️"
  },
  {
    id: "frame_06",
    name: "Supernova Radiante",
    category: "Cosmos",
    desc: "Uma explosão termonuclear cataclísmica de luz dourada e poeira estelar.",
    borderGradient: "linear-gradient(135deg, #f97316 0%, #ef4444 50%, #facc15 100%)",
    glowColor: "rgba(249, 115, 22, 0.7)",
    animationStyle: "fire-aura",
    requiredXp: 400,
    emojiSymbol: "💥",
    badgeText: "Raro"
  },
  {
    id: "frame_07",
    name: "Constelação Guardiã",
    category: "Cosmos",
    desc: "Estrelas guias fixadas no infinito desenhando novos caminhos.",
    borderGradient: "radial-gradient(circle, #fef08a 0%, #3b82f6 80%, #1d4ed8 100%)",
    glowColor: "rgba(254, 240, 138, 0.5)",
    animationStyle: "stars-shimmer",
    requiredXp: 550,
    emojiSymbol: "✨"
  },
  {
    id: "frame_08",
    name: "Matéria Escura",
    category: "Cosmos",
    desc: "Responsável pela maior parte do componente de massa no universo visível.",
    borderGradient: "linear-gradient(to right, #090514, #2e0854, #4a127a)",
    glowColor: "rgba(74, 18, 122, 0.6)",
    animationStyle: "pulse-glow",
    requiredXp: 700,
    emojiSymbol: "🔮"
  },
  {
    id: "frame_09",
    name: "Quasar Alimentado",
    category: "Cosmos",
    desc: "Feixes duplos de energia ultravioleta e ondas de rádio supermassivos.",
    borderGradient: "linear-gradient(180deg, #a855f7 0%, #06b6d4 100%)",
    glowColor: "rgba(168, 85, 247, 0.6)",
    animationStyle: "rainbow-flow",
    requiredXp: 900,
    emojiSymbol: "🛰️"
  },
  {
    id: "frame_10",
    name: "Nuvem de Oort",
    category: "Cosmos",
    desc: "Um escudo circular imenso composto por bilhões de gelos espaciais e cometas.",
    borderGradient: "linear-gradient(135deg, #38bdf8 0%, #bae6fd 60%, #e0f2fe 100%)",
    glowColor: "rgba(186, 230, 253, 0.5)",
    animationStyle: "orbit-gems",
    requiredXp: 1100,
    emojiSymbol: "❄️"
  },

  // CATEGORY: Cyberpunk
  {
    id: "frame_11",
    name: "Grelha Cibernética",
    category: "Cyberpunk",
    desc: "Grade holográfica de laser verde projetada diretamente na retina.",
    borderGradient: "linear-gradient(90deg, #10b981 0%, #059669 100%)",
    glowColor: "rgba(16, 185, 129, 0.5)",
    animationStyle: "spin-slow",
    requiredXp: 120,
    emojiSymbol: "📟"
  },
  {
    id: "frame_12",
    name: "Neon Tóxico",
    category: "Cyberpunk",
    desc: "A cor proibida dos clubes subterrâneos das megalópoles futuristas.",
    borderGradient: "linear-gradient(45deg, #84cc16 0%, #22c55e 100%)",
    glowColor: "rgba(132, 204, 22, 0.6)",
    animationStyle: "neon-flicker",
    requiredXp: 200,
    emojiSymbol: "🧪"
  },
  {
    id: "frame_13",
    name: "Chuva Digital",
    category: "Cyberpunk",
    desc: "Símbolos e algarismos binários escorrendo em tempo real na tela do console.",
    borderGradient: "linear-gradient(180deg, #22c55e 0%, #000000 100%)",
    glowColor: "rgba(34, 197, 94, 0.6)",
    animationStyle: "matrix-rain",
    requiredXp: 300,
    emojiSymbol: "💾",
    badgeText: "Hacker"
  },
  {
    id: "frame_14",
    name: "Holograma Instável",
    category: "Cyberpunk",
    desc: "Efeito de glitch analógico intermitente devido a mau contato na fiação.",
    borderGradient: "linear-gradient(90deg, #06b6d4 0%, #ec4899 50%, #06b6d4 100%)",
    glowColor: "rgba(6, 182, 212, 0.6)",
    animationStyle: "neon-flicker",
    requiredXp: 425,
    emojiSymbol: "📡"
  },
  {
    id: "frame_15",
    name: "Linhas de Silício",
    category: "Cyberpunk",
    desc: "Terminais e barramentos folheados a ouro de alta condutividade lógica.",
    borderGradient: "linear-gradient(135deg, #eab308 0%, #ca8a04 50%, #451a03 100%)",
    glowColor: "rgba(234, 179, 8, 0.5)",
    animationStyle: "retro-lines",
    requiredXp: 575,
    emojiSymbol: "🔌"
  },
  {
    id: "frame_16",
    name: "Synthwave Sunset",
    category: "Cyberpunk",
    desc: "Entardecer pixelado clássico de Miami, 198X, com grades púrpuras.",
    borderGradient: "linear-gradient(180deg, #f43f5e 0%, #db2777 50%, #4a044e 100%)",
    glowColor: "rgba(244, 63, 94, 0.6)",
    animationStyle: "waves-flow",
    requiredXp: 750,
    emojiSymbol: "🌇"
  },
  {
    id: "frame_17",
    name: "Overclock Termo",
    category: "Cyberpunk",
    desc: "Aumentando a voltagem do processador até o limite do resfriamento líquido.",
    borderGradient: "linear-gradient(45deg, #ef4444 0%, #b91c1c 50%, #dc2626 100%)",
    glowColor: "rgba(239, 68, 68, 0.7)",
    animationStyle: "neon-flicker",
    requiredXp: 950,
    emojiSymbol: "🚨"
  },
  {
    id: "frame_18",
    name: "Reticulado Neural",
    category: "Cyberpunk",
    desc: "Rede sináptica bio-eletrônica para conexão cérebro-máquina instantânea.",
    borderGradient: "linear-gradient(to right, #3b82f6, #ec4899)",
    glowColor: "rgba(59, 130, 246, 0.5)",
    animationStyle: "orbit-gems",
    requiredXp: 1150,
    emojiSymbol: "🧠"
  },
  {
    id: "frame_19",
    name: "Estética Vapor",
    category: "Cyberpunk",
    desc: "Estátuas de mármore grego misturadas com sistema operacional de 1995.",
    borderGradient: "linear-gradient(135deg, #a5f3fc 0%, #f472b6 50%, #c084fc 100%)",
    glowColor: "rgba(192, 132, 252, 0.5)",
    animationStyle: "rainbow-flow",
    requiredXp: 1350,
    emojiSymbol: "🖼️"
  },
  {
    id: "frame_20",
    name: "Núcleo de Protocolo",
    category: "Cyberpunk",
    desc: "O centro de comando neural de inteligência mecânica criptografada.",
    borderGradient: "linear-gradient(90deg, #10b981 0%, #06b6d4 100%)",
    glowColor: "rgba(6, 182, 212, 0.7)",
    animationStyle: "spin-slow",
    requiredXp: 1600,
    emojiSymbol: "🛡️",
    badgeText: "Admin"
  },

  // CATEGORY: Místico / Magia
  {
    id: "frame_21",
    name: "Névoa Élfica",
    category: "Místico",
    desc: "Sussurros antigos das árvores centenárias da floresta sagrada.",
    borderGradient: "linear-gradient(135deg, #d9f99d 0%, #22c55e 100%)",
    glowColor: "rgba(34, 197, 94, 0.4)",
    animationStyle: "pulse-glow",
    requiredXp: 150,
    emojiSymbol: "🍃"
  },
  {
    id: "frame_22",
    name: "Renascimento da Fênix",
    category: "Místico",
    desc: "Renascido das cinzas celestes em chamas perpétuas de sabedoria.",
    borderGradient: "linear-gradient(90deg, #dc2626 0%, #f97316 50%, #facc15 100%)",
    glowColor: "rgba(220, 38, 38, 0.7)",
    animationStyle: "fire-aura",
    requiredXp: 320,
    emojiSymbol: "🐦‍🔥",
    badgeText: "Eterno"
  },
  {
    id: "frame_23",
    name: "Chamas de Fafnir",
    category: "Místico",
    desc: "Rastro abrasador do sopro do dragão ancestral do abismo de magma.",
    borderGradient: "linear-gradient(135deg, #991b1b 0%, #ea580c 100%)",
    glowColor: "rgba(234, 88, 12, 0.7)",
    animationStyle: "fire-aura",
    requiredXp: 520,
    emojiSymbol: "🐉"
  },
  {
    id: "frame_24",
    name: "Abismo Profundo",
    category: "Místico",
    desc: "A fosforescência das criaturas abissais no fundo imensurável do mar.",
    borderGradient: "linear-gradient(225deg, #1e3a8a 0%, #0d9488 100%)",
    glowColor: "rgba(13, 148, 136, 0.5)",
    animationStyle: "waves-flow",
    requiredXp: 720,
    emojiSymbol: "🐙"
  },
  {
    id: "frame_25",
    name: "Auréola Sagrada",
    category: "Místico",
    desc: "Um círculo de luz canônica dourada que irradia paz intocável.",
    borderGradient: "radial-gradient(circle, #fef08a 0%, #eab308 60%, #ffffff 100%)",
    glowColor: "rgba(234, 179, 8, 0.6)",
    animationStyle: "stars-shimmer",
    requiredXp: 920,
    emojiSymbol: "😇"
  },
  {
    id: "frame_26",
    name: "Fogo Infernal",
    category: "Místico",
    desc: "Wisps de chamas espectrais violetas e verdes vindos do submundo.",
    borderGradient: "linear-gradient(45deg, #c084fc 0%, #4ade80 100%)",
    glowColor: "rgba(192, 132, 252, 0.6)",
    animationStyle: "neon-flicker",
    requiredXp: 1120,
    emojiSymbol: "💀"
  },
  {
    id: "frame_27",
    name: "Nexo Arcano",
    category: "Místico",
    desc: "A conjunção mágica onde toda a conjuração de conhecimento é amplificada.",
    borderGradient: "linear-gradient(135deg, #a855f7 0%, #6366f1 100%)",
    glowColor: "rgba(168, 85, 247, 0.6)",
    animationStyle: "spin-slow",
    requiredXp: 1320,
    emojiSymbol: "🔮"
  },
  {
    id: "frame_28",
    name: "Pó de Fada",
    category: "Místico",
    desc: "Partículas de purpurina cintilantes que permitem levitar pensamentos.",
    borderGradient: "linear-gradient(90deg, #f472b6 0%, #f43f5e 50%, #ec4899 100%)",
    glowColor: "rgba(244, 114, 182, 0.6)",
    animationStyle: "stars-shimmer",
    requiredXp: 1520,
    emojiSymbol: "🪄"
  },
  {
    id: "frame_29",
    name: "Runa Hibernante",
    category: "Místico",
    desc: "Inscrições antigas adormecidas gravadas no granito que acendem com magia.",
    borderGradient: "linear-gradient(135deg, #0ea5e9 0%, #1e1b4b 100%)",
    glowColor: "rgba(14, 165, 233, 0.5)",
    animationStyle: "pulse-glow",
    requiredXp: 1750,
    emojiSymbol: "📜"
  },
  {
    id: "frame_30",
    name: "Olho do Guardião",
    category: "Místico",
    desc: "Um foco psíquico que tudo vê e tudo entende a respeito do destino.",
    borderGradient: "linear-gradient(270deg, #ff007f 0%, #7f00ff 100%)",
    glowColor: "rgba(127, 0, 255, 0.7)",
    animationStyle: "rainbow-flow",
    requiredXp: 2050,
    emojiSymbol: "👁️",
    badgeText: "Oráculo"
  },

  // CATEGORY: Imperial / Nobreza / Luxo
  {
    id: "frame_31",
    name: "Ouro Maciço 24K",
    category: "Imperial",
    desc: "Bordas forjadas em puro ouro fundido sob alta pressão.",
    borderGradient: "linear-gradient(135deg, #fbbf24 0%, #f59e0b 50%, #d97706 100%)",
    glowColor: "rgba(245, 158, 11, 0.5)",
    animationStyle: "pulse-glow",
    requiredXp: 250,
    emojiSymbol: "🏆"
  },
  {
    id: "frame_32",
    name: "Cresta de Diamantes",
    category: "Imperial",
    desc: "Cravejada com diamantes lapidados que refletem prismas arco-íris.",
    borderGradient: "linear-gradient(45deg, #ffffff 0%, #e2e8f0 50%, #cbd5e1 100%)",
    glowColor: "rgba(255, 255, 255, 0.6)",
    animationStyle: "stars-shimmer",
    requiredXp: 450,
    emojiSymbol: "💎"
  },
  {
    id: "frame_33",
    name: "Veludo Imperial",
    category: "Imperial",
    desc: "Bordas acolchoadas em vermelho escarlate da dinastia governante.",
    borderGradient: "linear-gradient(135deg, #991b1b 0%, #7f1d1d 60%, #b45309 100%)",
    glowColor: "rgba(153, 27, 27, 0.5)",
    animationStyle: "retro-lines",
    requiredXp: 650,
    emojiSymbol: "👑"
  },
  {
    id: "frame_34",
    name: "Esmeralda Nobre",
    category: "Imperial",
    desc: "Uma lapidação esmeralda circular perfeita herdada por imperadores.",
    borderGradient: "linear-gradient(90deg, #047857 0%, #10b981 50%, #064e3b 100%)",
    glowColor: "rgba(16, 185, 129, 0.5)",
    animationStyle: "pulse-glow",
    requiredXp: 850,
    emojiSymbol: "💚"
  },
  {
    id: "frame_35",
    name: "Prata de Filigrana",
    category: "Imperial",
    desc: "Trançado artesanal precioso feito de fibra pura de prata estelar.",
    borderGradient: "linear-gradient(135deg, #94a3b8 0%, #cbd5e1 50%, #f1f5f9 100%)",
    glowColor: "rgba(203, 213, 225, 0.5)",
    animationStyle: "orbit-gems",
    requiredXp: 1050,
    emojiSymbol: "🪙"
  },
  {
    id: "frame_36",
    name: "Louros do Triunfo",
    category: "Imperial",
    desc: "A icônica coroa de ramos de louros concedida aos generais vencedores.",
    borderGradient: "linear-gradient(to right, #15803d, #4ade80, #166534)",
    glowColor: "rgba(74, 222, 128, 0.4)",
    animationStyle: "pulse-glow",
    requiredXp: 1250,
    emojiSymbol: "🌿",
    badgeText: "Vencedor"
  },
  {
    id: "frame_37",
    name: "Aura Platina",
    category: "Imperial",
    desc: "Alcançou o estado imaculado do metal de transição mais denso e valioso.",
    borderGradient: "linear-gradient(135deg, #e2e8f0 0%, #94a3b8 50%, #334155 100%)",
    glowColor: "rgba(226, 232, 240, 0.5)",
    animationStyle: "rainbow-flow",
    requiredXp: 1550,
    emojiSymbol: "🎖️"
  },
  {
    id: "frame_38",
    name: "Coroa Vitoriosa",
    category: "Imperial",
    desc: "O símbolo máximo de autoridade educacional sobre o cosmos.",
    borderGradient: "linear-gradient(45deg, #fbbf24 0%, #fef08a 30%, #f59e0b 70%, #d97706 100%)",
    glowColor: "rgba(251, 191, 36, 0.7)",
    animationStyle: "orbit-gems",
    requiredXp: 1900,
    emojiSymbol: "👑",
    badgeText: "Realeza"
  },
  {
    id: "frame_39",
    name: "Opala Arco-Íris",
    category: "Imperial",
    desc: "Gema que reflete todas as cores cósmicas dependendo do ângulo da luz.",
    borderGradient: "linear-gradient(90deg, #fdba74 0%, #f472b6 25%, #a5b4fc 50%, #93c5fd 75%, #34d399 100%)",
    glowColor: "rgba(244, 114, 182, 0.6)",
    animationStyle: "rainbow-flow",
    requiredXp: 2300,
    emojiSymbol: "🦪"
  },
  {
    id: "frame_40",
    name: "Cordão de Pérolas",
    category: "Imperial",
    desc: "Pérolas do oceano selecionadas individualmente e encadeadas em harmonia.",
    borderGradient: "radial-gradient(circle, #ffffff 0%, #f1f5f9 60%, #cbd5e1 100%)",
    glowColor: "rgba(255, 255, 255, 0.5)",
    animationStyle: "orbit-gems",
    requiredXp: 2700,
    emojiSymbol: "📿",
    badgeText: "Lendário"
  },

  // CATEGORY: Elemental
  {
    id: "frame_41",
    name: "Mar de Tétis",
    category: "Elemental",
    desc: "Abraçado pelo fluxo incessante e pacífico das correntes marinhas.",
    borderGradient: "linear-gradient(180deg, #06b6d4 0%, #3b82f6 100%)",
    glowColor: "rgba(6, 182, 212, 0.5)",
    animationStyle: "waves-flow",
    requiredXp: 160,
    emojiSymbol: "🌊"
  },
  {
    id: "frame_42",
    name: "Fissura de Vulcano",
    category: "Elemental",
    desc: "Rocha vulcânica rachada expondo o magma puro incandescente do manto.",
    borderGradient: "linear-gradient(135deg, #b91c1c 0%, #f97316 60%, #450a0a 100%)",
    glowColor: "rgba(185, 28, 28, 0.7)",
    animationStyle: "fire-aura",
    requiredXp: 330,
    emojiSymbol: "🌋"
  },
  {
    id: "frame_43",
    name: "Vento do Zéfiro",
    category: "Elemental",
    desc: "Roda de brisa ciclônica invisível que canaliza força cinética intelectual.",
    borderGradient: "linear-gradient(45deg, #a5f3fc 0%, #e0f2fe 100%)",
    glowColor: "rgba(165, 243, 252, 0.4)",
    animationStyle: "waves-flow",
    requiredXp: 530,
    emojiSymbol: "🌀"
  },
  {
    id: "frame_44",
    name: "Flor da Terra",
    category: "Elemental",
    desc: "Viras e brotos que nascem de solos adubados pela dedicação.",
    borderGradient: "linear-gradient(135deg, #10b981 0%, #84cc16 50%, #78350f 100%)",
    glowColor: "rgba(132, 204, 22, 0.4)",
    animationStyle: "pulse-glow",
    requiredXp: 730,
    emojiSymbol: "🌻"
  },
  {
    id: "frame_45",
    name: "Relâmpago de Zeus",
    category: "Elemental",
    desc: "Alta descarga estática descarregando megawatts de potência mental.",
    borderGradient: "linear-gradient(90deg, #facc15 0%, #eab308 50%, #ffffff 100%)",
    glowColor: "rgba(250, 204, 21, 0.6)",
    animationStyle: "neon-flicker",
    requiredXp: 1000,
    emojiSymbol: "⚡",
    badgeText: "Dinâmico"
  },
  {
    id: "frame_46",
    name: "Frágil Cristal",
    category: "Elemental",
    desc: "Bordas de geleira gelada que emitem névoa criogênica e reflexos frios.",
    borderGradient: "linear-gradient(135deg, #e0f2fe 0%, #38bdf8 60%, #bae6fd 100%)",
    glowColor: "rgba(56, 189, 248, 0.5)",
    animationStyle: "stars-shimmer",
    requiredXp: 1220,
    emojiSymbol: "❄️"
  },
  {
    id: "frame_47",
    name: "Brigo de Sombras",
    category: "Elemental",
    desc: "Fumaça mística de éter sombrio que flutua silenciosamente.",
    borderGradient: "linear-gradient(225deg, #09090b 0%, #27272a 60%, #18181b 100%)",
    glowColor: "rgba(39, 39, 42, 0.4)",
    animationStyle: "pulse-glow",
    requiredXp: 1520,
    emojiSymbol: "🖤"
  },
  {
    id: "frame_48",
    name: "Hora Dourada",
    category: "Elemental",
    desc: "Os gloriosos minutos em que o Sol beija o horizonte e doura o mundo.",
    borderGradient: "linear-gradient(180deg, #f59e0b 0%, #f97316 50%, #b45309 100%)",
    glowColor: "rgba(245, 158, 11, 0.6)",
    animationStyle: "waves-flow",
    requiredXp: 1850,
    emojiSymbol: "🌅"
  },
  {
    id: "frame_49",
    name: "Eclipse Corona",
    category: "Elemental",
    desc: "O alinhamento absoluto onde a escuridão coroa uma coroa solar flamejante.",
    borderGradient: "radial-gradient(circle, #000000 30%, #ffffff 70%, #f97316 100%)",
    glowColor: "rgba(255, 255, 255, 0.7)",
    animationStyle: "fire-aura",
    requiredXp: 2250,
    emojiSymbol: "🌑"
  },
  {
    id: "frame_50",
    name: "Lua de Sangue",
    category: "Elemental",
    desc: "A profecia escarlate no céu noturno das mentes mais brilhantes e vorazes.",
    borderGradient: "linear-gradient(45deg, #7f1d1d 0%, #dc2626 50%, #000000 100%)",
    glowColor: "rgba(220, 38, 38, 0.8)",
    animationStyle: "fire-aura",
    requiredXp: 3000,
    emojiSymbol: "🩸",
    badgeText: "Eclipse"
  },
  // --- EXCLUSIVE PREMIUM FRAMES (50 NEW PIECES) ---
  // CATEGORY: Cosmos (51 to 60)
  {
    id: "frame_51",
    name: "Horizonte de Eventos Prime",
    category: "Cosmos",
    desc: "A fronteira gravitacional final onde o próprio espaço-tempo se deforma majestosamente.",
    borderGradient: "linear-gradient(135deg, #7c3aed 0%, #000000 100%)",
    glowColor: "rgba(124, 58, 237, 0.8)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "🕳️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_52",
    name: "Estrela de Nêutrons Prime",
    category: "Cosmos",
    desc: "Uma densidade incompreensível irradiando feixes azuis ultra-violeta de foco absoluto.",
    borderGradient: "linear-gradient(45deg, #06b6d4 0%, #ffffff 50%, #3b82f6 100%)",
    glowColor: "rgba(6, 182, 212, 0.8)",
    animationStyle: "neon-flicker",
    requiredXp: 0,
    emojiSymbol: "✨",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_53",
    name: "Singularidade Cósmica",
    category: "Cosmos",
    desc: "O ponto focal de densidade e brilho infinitos no coração do colapso cósmico.",
    borderGradient: "linear-gradient(225deg, #1e1b4b 0%, #ec4899 50%, #000000 100%)",
    glowColor: "rgba(236, 72, 153, 0.8)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "🌟",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_54",
    name: "Hiperespaço Dimensional",
    category: "Cosmos",
    desc: "Dobre o contínuo acadêmico com este propulsor hyperdrive cósmico de elite.",
    borderGradient: "linear-gradient(90deg, #6366f1 0%, #a855f7 100%)",
    glowColor: "rgba(168, 85, 247, 0.7)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "☄️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_55",
    name: "Super-Aglomerado Laniakea",
    category: "Cosmos",
    desc: "O imenso mapa de cem mil galáxias unidas no brilho da alta gravidade do saber.",
    borderGradient: "linear-gradient(135deg, #ec4899 0%, #3b82f6 100%)",
    glowColor: "rgba(59, 130, 246, 0.7)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "🌌",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_56",
    name: "Antimatéria Efêmera",
    category: "Cosmos",
    desc: "Energia radiante gerada pelo choque de elementos opostos no infinito cósmico.",
    borderGradient: "linear-gradient(90deg, #dc2626 0%, #06b6d4 100%)",
    glowColor: "rgba(6, 182, 212, 0.8)",
    animationStyle: "neon-flicker",
    requiredXp: 0,
    emojiSymbol: "🔋",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_57",
    name: "Sopro de Quasar",
    category: "Cosmos",
    desc: "Feixes duplos e colossais de luz ultravioleta emitidos à velocidade relativística.",
    borderGradient: "linear-gradient(45deg, #f43f5e 0%, #eab308 100%)",
    glowColor: "rgba(244, 63, 148, 0.8)",
    animationStyle: "fire-aura",
    requiredXp: 0,
    emojiSymbol: "🛸",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_58",
    name: "Nebulosa de Ampulheta",
    category: "Cosmos",
    desc: "Gases quentes e incandescentes expandindo-se no tempo canônico das estrelas.",
    borderGradient: "linear-gradient(180deg, #f97316 0%, #a855f7 100%)",
    glowColor: "rgba(249, 115, 22, 0.7)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "⏳",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_59",
    name: "Radiação de Fundo",
    category: "Cosmos",
    desc: "O majestoso e silencioso eco eletromagnético da grande explosão do saber.",
    borderGradient: "linear-gradient(135deg, #14b8a6 0%, #a855f7 100%)",
    glowColor: "rgba(168, 85, 247, 0.7)",
    animationStyle: "orbit-gems",
    requiredXp: 0,
    emojiSymbol: "📡",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_60",
    name: "Poeira Primordial",
    category: "Cosmos",
    desc: "Moldura cintilante provando que somos construídos da essência estelar nobre.",
    borderGradient: "linear-gradient(to right, #fbbf24, #ec4899, #3b82f6)",
    glowColor: "rgba(236, 72, 153, 0.8)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "☄️",
    badgeText: "DEUS ESTELAR",
    badgeColor: "bg-red-600 bg-gradient-to-r from-red-500 to-orange-500 animate-pulse",
    isPremiumOnly: true
  },

  // CATEGORY: Cyberpunk (61 to 70)
  {
    id: "frame_61",
    name: "IA Consciência Suprema",
    category: "Cyberpunk",
    desc: "Código autônomo e autoconsciente que molda o próprio destino digital.",
    borderGradient: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
    glowColor: "rgba(16, 185, 129, 0.75)",
    animationStyle: "neon-flicker",
    requiredXp: 0,
    emojiSymbol: "🤖",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_62",
    name: "Glicose Digital XL",
    category: "Cyberpunk",
    desc: "Fluido purificado para criogenia de superprocessadores em alto overclock.",
    borderGradient: "linear-gradient(45deg, #22c55e 0%, #ef4444 100%)",
    glowColor: "rgba(34, 197, 94, 0.7)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "🧪",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_63",
    name: "Escudo do Firewall",
    category: "Cyberpunk",
    desc: "Imunidade quântica absoluta contra escaneamentos ou quedas de internet.",
    borderGradient: "linear-gradient(225deg, #1e293b 0%, #cbd5e1 50%, #0f172a 100%)",
    glowColor: "rgba(203, 213, 225, 0.6)",
    animationStyle: "retro-lines",
    requiredXp: 0,
    emojiSymbol: "🛡️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_64",
    name: "Córtex Tático 5.0",
    category: "Cyberpunk",
    desc: "Melhoria biônica premium que acelera o fluxo de conexões sinápticas cerebrais.",
    borderGradient: "linear-gradient(90deg, #0ea5e9 0%, #ec4899 100%)",
    glowColor: "rgba(14, 165, 233, 0.7)",
    animationStyle: "retro-lines",
    requiredXp: 0,
    emojiSymbol: "🧠",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_65",
    name: "Vetor Holográfico",
    category: "Cyberpunk",
    desc: "Grades de laser vetorizadas desenhando novas dimensões no terminal virtual.",
    borderGradient: "linear-gradient(180deg, #d946ef 0%, #06b6d4 100%)",
    glowColor: "rgba(217, 70, 239, 0.7)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "📐",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_66",
    name: "Ciber-Decadência Real",
    category: "Cyberpunk",
    desc: "O contraste poético entre o neon do alto luxo e barramentos folheados.",
    borderGradient: "linear-gradient(135deg, #dc2626 0%, #475569 100%)",
    glowColor: "rgba(220, 38, 38, 0.7)",
    animationStyle: "neon-flicker",
    requiredXp: 0,
    emojiSymbol: "🔌",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_67",
    name: "Blade Runner Skyline",
    category: "Cyberpunk",
    desc: "O icônico contorno metropolitano das torres corporativas corporificadas.",
    borderGradient: "linear-gradient(45deg, #3b82f6 0%, #f43f5e 100%)",
    glowColor: "rgba(244, 63, 94, 0.72)",
    animationStyle: "matrix-rain",
    requiredXp: 0,
    emojiSymbol: "🌇",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_68",
    name: "Grelha Hacker Silenciosa",
    category: "Cyberpunk",
    desc: "Varredura silenciosa e ágil por túneis de fibra óptica criptografados.",
    borderGradient: "linear-gradient(90deg, #10b981 0%, #15803d 100%)",
    glowColor: "rgba(16, 185, 129, 0.7)",
    animationStyle: "matrix-rain",
    requiredXp: 0,
    emojiSymbol: "💻",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_69",
    name: "Neon de Shibuya 2099",
    category: "Cyberpunk",
    desc: "Inundação de luzes rosas de alta saturação recriadas em fluxo contínuo.",
    borderGradient: "linear-gradient(180deg, #ec4899 0%, #8b5cf6 100%)",
    glowColor: "rgba(236, 72, 153, 0.75)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "🗼",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_70",
    name: "Elite do Tecno-Vácuo",
    category: "Cyberpunk",
    desc: "Interface imersiva definitiva dos hackers e deuses do deslumbrante ciberespaço.",
    borderGradient: "linear-gradient(to right, #000000, #ec4899, #00f0ff)",
    glowColor: "rgba(0, 240, 255, 0.8)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "🛰️",
    badgeText: "Ciber-Deus",
    badgeColor: "bg-fuchsia-600 bg-gradient-to-r from-fuchsia-500 to-amber-500 animate-bounce",
    isPremiumOnly: true
  },

  // CATEGORY: Místico (71 to 80)
  {
    id: "frame_71",
    name: "Eternidade Estelar",
    category: "Místico",
    desc: "Poeira de estrelas condensada em benção infinita e vitalidade espiritual.",
    borderGradient: "linear-gradient(135deg, #fef08a 0%, #eab308 100%)",
    glowColor: "rgba(234, 179, 8, 0.7)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "🪄",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_72",
    name: "Néctar dos Olimpianos",
    category: "Místico",
    desc: "O elixir sagrado que purifica os medos intelectuais e concede fôlego.",
    borderGradient: "linear-gradient(45deg, #fb923c 0%, #db2777 100%)",
    glowColor: "rgba(219, 39, 119, 0.75)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "🍯",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_73",
    name: "Tomo do Arcano Proibido",
    category: "Místico",
    desc: "Inscrições arcanas pulsantes que revelam as verdades profundas das galáxias.",
    borderGradient: "linear-gradient(225deg, #4c1d95 0%, #a855f7 100%)",
    glowColor: "rgba(168, 85, 247, 0.75)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "📚",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_74",
    name: "Olho de Hórus Sagrado",
    category: "Místico",
    desc: "Amuleto egípcio de proteção e visão absoluta que atravessa realidades.",
    borderGradient: "linear-gradient(90deg, #f59e0b 0%, #10b981 100%)",
    glowColor: "rgba(245, 158, 11, 0.7)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "📿",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_75",
    name: "Sopro de Frio Absoluto",
    category: "Místico",
    desc: "Corrente de névoa congelante e canônica gerada no manto de gelo sideral.",
    borderGradient: "linear-gradient(135deg, #e2e8f0 0%, #06b6d4 100%)",
    glowColor: "rgba(6, 182, 212, 0.7)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "🌬️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_76",
    name: "Alquimia do Conhecimento",
    category: "Místico",
    desc: "A misteriosa transmutação de estudo árduo em conquista espiritual dourada.",
    borderGradient: "linear-gradient(90deg, #a855f7 0%, #fbbf24 100%)",
    glowColor: "rgba(251, 191, 36, 0.7)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "🪙",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_77",
    name: "Coração Étereo",
    category: "Místico",
    desc: "A essência silenciosa que alimenta o nexo cósmico e protege a sua mente.",
    borderGradient: "linear-gradient(45deg, #38bdf8 0%, #c084fc 100%)",
    glowColor: "rgba(192, 132, 252, 0.7)",
    animationStyle: "orbit-gems",
    requiredXp: 0,
    emojiSymbol: "🔮",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_78",
    name: "Bússola de Atlântida",
    category: "Místico",
    desc: "Uma guia perdida nas ruínas oceânicas que aponta os caminhos da glória.",
    borderGradient: "linear-gradient(180deg, #0d9488 0%, #bae6fd 100%)",
    glowColor: "rgba(13, 148, 136, 0.7)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "🧭",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_79",
    name: "Chama Escarlate da Fênix",
    category: "Místico",
    desc: "Renascimento diário e calor inesgotável da ave lendária de fogo.",
    borderGradient: "linear-gradient(135deg, #ef4444 0%, #f59e0b 100%)",
    glowColor: "rgba(239, 68, 68, 0.8)",
    animationStyle: "fire-aura",
    requiredXp: 0,
    emojiSymbol: "🐦‍🔥",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_80",
    name: "Oráculo da Semente Sábia",
    category: "Místico",
    desc: "O manto místico perfeito desenhado para as mentes de foco absoluto e imutável.",
    borderGradient: "linear-gradient(to right, #7f00ff, #e100ff, #00ddff)",
    glowColor: "rgba(127, 0, 255, 0.82)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "🌟",
    badgeText: "Mestre Oráculo",
    badgeColor: "bg-indigo-600 bg-gradient-to-r from-indigo-500 to-cyan-500",
    isPremiumOnly: true
  },

  // CATEGORY: Imperial (81 to 90)
  {
    id: "frame_81",
    name: "Coroa Sideral Imperial",
    category: "Imperial",
    desc: "Concebida em platina pura e adornada com as mais preciosas gemas galácticas.",
    borderGradient: "linear-gradient(135deg, #ffffff 0%, #cbd5e1 50%, #94a3b8 100%)",
    glowColor: "rgba(226, 232, 240, 0.75)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "👑",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_82",
    name: "Sinete Nobre de Ouro",
    category: "Imperial",
    desc: "O anel de chancela privativa reservado apenas aos acadêmicos de linhagem nobre.",
    borderGradient: "linear-gradient(45deg, #f59e0b 0%, #fbbf24 100%)",
    glowColor: "rgba(245, 158, 11, 0.75)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "💍",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_83",
    name: "Esplendor de Safira",
    category: "Imperial",
    desc: "Brilho azul profundo e inabalável herdado pelas maiores cortes reais.",
    borderGradient: "linear-gradient(225deg, #1d4ed8 0%, #3b82f6 100%)",
    glowColor: "rgba(29, 78, 216, 0.75)",
    animationStyle: "orbit-gems",
    requiredXp: 0,
    emojiSymbol: "🔷",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_84",
    name: "Trânsito de Rubi Imperial",
    category: "Imperial",
    desc: "Feita com gemas carmesim raras polidas individualmente na forja real.",
    borderGradient: "linear-gradient(90deg, #be123c 0%, #fda4af 100%)",
    glowColor: "rgba(190, 18, 60, 0.75)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "💎",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_85",
    name: "Mármore da Dinastia",
    category: "Imperial",
    desc: "Bordas texturizadas simulando pilares monárquicos polidos com ranhuras em ouro.",
    borderGradient: "linear-gradient(135deg, #fafaf9 0%, #f59e0b 100%)",
    glowColor: "rgba(245, 158, 11, 0.65)",
    animationStyle: "retro-lines",
    requiredXp: 0,
    emojiSymbol: "🏛️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_86",
    name: "Tapeçaria Real Escarlate",
    category: "Imperial",
    desc: "Veludo vermelho dinástico imerso em fios de condutividade de alta nobreza.",
    borderGradient: "linear-gradient(90deg, #991b1b 0%, #f43f5e 100%)",
    glowColor: "rgba(244, 63, 94, 0.7)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "🥋",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_87",
    name: "Esmeralda do Palácio",
    category: "Imperial",
    desc: "Uma lapidação esmeralda circular fascinante repleta de joias de alta qualidade.",
    borderGradient: "linear-gradient(45deg, #059669 0%, #34d399 100%)",
    glowColor: "rgba(5, 150, 105, 0.75)",
    animationStyle: "spin-slow",
    requiredXp: 0,
    emojiSymbol: "🟢",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_88",
    name: "Trança de Filigrana Branca",
    category: "Imperial",
    desc: "Fios entrelaçados de ouro branco e prata estelar de alta condutividade.",
    borderGradient: "linear-gradient(180deg, #cbd5e1 0%, #f1f5f9 100%)",
    glowColor: "rgba(203, 213, 225, 0.7)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "⛓️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_89",
    name: "Ramos da Vitória Eterna",
    category: "Imperial",
    desc: "A guirlanda monárquica folheada a platina outorgada aos sábios maiores.",
    borderGradient: "linear-gradient(135deg, #a855f7 0%, #db2777 100%)",
    glowColor: "rgba(168, 85, 247, 0.75)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "🌿",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_90",
    name: "Soberania do Cosmos Prime",
    category: "Imperial",
    desc: "O troféu definitivo de prestígio que coroa o rei supremo das constelações.",
    borderGradient: "linear-gradient(to right, #fbbf24, #f59e0b, #d97706)",
    glowColor: "rgba(245, 158, 11, 0.85)",
    animationStyle: "orbit-gems",
    requiredXp: 0,
    emojiSymbol: "🏆",
    badgeText: "Imperador do Saber",
    badgeColor: "bg-amber-500 bg-gradient-to-r from-amber-500 to-yellow-500 font-black tracking-wide",
    isPremiumOnly: true
  },

  // CATEGORY: Elemental (91 to 100)
  {
    id: "frame_91",
    name: "Magma do Manto",
    category: "Elemental",
    desc: "Pedra vulcânica rachada revelando o fluxo incandescente da determinação.",
    borderGradient: "linear-gradient(135deg, #b91c1c 0%, #ea580c 100%)",
    glowColor: "rgba(185, 28, 28, 0.8)",
    animationStyle: "fire-aura",
    requiredXp: 0,
    emojiSymbol: "🌋",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_92",
    name: "Geleira Criogênica Prime",
    category: "Elemental",
    desc: "Gelo denso formado sob pressões abissais que exala névoa criogênica.",
    borderGradient: "linear-gradient(45deg, #e0f2fe 0%, #0ea5e9 100%)",
    glowColor: "rgba(14, 165, 233, 0.75)",
    animationStyle: "stars-shimmer",
    requiredXp: 0,
    emojiSymbol: "❄️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_93",
    name: "Ciclone Primordial",
    category: "Elemental",
    desc: "Ventos revoltos em turbilhão contínuo que eliminam qualquer barreira mental.",
    borderGradient: "linear-gradient(225deg, #cbd5e1 0%, #38bdf8 100%)",
    glowColor: "rgba(56, 189, 248, 0.7)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "🌀",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_94",
    name: "Fagulha Térmica",
    category: "Elemental",
    desc: "Descargas elétricas ionizadas cruzando a atmosfera em velocidades supersônicas.",
    borderGradient: "linear-gradient(90deg, #a855f7 0%, #6366f1 100%)",
    glowColor: "rgba(168, 85, 247, 0.75)",
    animationStyle: "neon-flicker",
    requiredXp: 0,
    emojiSymbol: "⚡",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_95",
    name: "Éter Elemental",
    category: "Elemental",
    desc: "O misterioso e intangível brilho gasoso que equilibra as energias estelares.",
    borderGradient: "linear-gradient(180deg, #f472b6 0%, #a7f3d0 100%)",
    glowColor: "rgba(244, 114, 182, 0.7)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "🍃",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_96",
    name: "Chama Azul Perfeita",
    category: "Elemental",
    desc: "A queima molecular superaquecida que indica o mais alto índice de foco do cérebro.",
    borderGradient: "linear-gradient(135deg, #1d4ed8 0%, #00f0ff 100%)",
    glowColor: "rgba(0, 240, 255, 0.8)",
    animationStyle: "fire-aura",
    requiredXp: 0,
    emojiSymbol: "🔥",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_97",
    name: "Manto Flora Cósmica",
    category: "Elemental",
    desc: "Ramos botânicos centenários alimentados com poeira e orvalho das estrelas primas.",
    borderGradient: "linear-gradient(45deg, #166534 0%, #86efac 100%)",
    glowColor: "rgba(22, 101, 52, 0.7)",
    animationStyle: "pulse-glow",
    requiredXp: 0,
    emojiSymbol: "🍂",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_98",
    name: "Tempestade de Cometas",
    category: "Elemental",
    desc: "A combustão brilhante de poeira e detritos orbitando os céus das mentes ágeis.",
    borderGradient: "linear-gradient(90deg, #f97316 0%, #dc2626 100%)",
    glowColor: "rgba(220, 38, 38, 0.78)",
    animationStyle: "orbit-gems",
    requiredXp: 0,
    emojiSymbol: "💫",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_99",
    name: "Solstício Radiante 24K",
    category: "Elemental",
    desc: "O brilho absoluto do meio-dia capturado em uma circunferência de ouro e fogo.",
    borderGradient: "linear-gradient(180deg, #facc15 0%, #f97316 100%)",
    glowColor: "rgba(250, 204, 21, 0.8)",
    animationStyle: "waves-flow",
    requiredXp: 0,
    emojiSymbol: "☀️",
    badgeText: "PREMIUM",
    badgeColor: "bg-purple-600 bg-gradient-to-r from-purple-500 to-indigo-600",
    isPremiumOnly: true
  },
  {
    id: "frame_100",
    name: "Avatar Cósmico Supremo",
    category: "Elemental",
    desc: "O equilíbrio mestre de todos os elementos naturais e transcendentais da galáxia.",
    borderGradient: "linear-gradient(to right, #ef4444, #3b82f6, #10b981, #facc15)",
    glowColor: "rgba(59, 130, 246, 0.85)",
    animationStyle: "rainbow-flow",
    requiredXp: 0,
    emojiSymbol: "🥋",
    badgeText: "Mestre Alquimista",
    badgeColor: "bg-emerald-500 bg-gradient-to-r from-emerald-500 to-teal-500 font-extrabold animate-pulse",
    isPremiumOnly: true
  }
];
